version: '3'
services:
  hello-express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:8080'
    cpus: 1
    # cpu_period: '1'
    # cpu_quota: '0.5'
    # mem_reservation: 128m
    mem_limit: 512m